"use client";

import {
  Baby,
  Banknote,
  BedDouble,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Cake,
  Car,
  CircleDashed,
  Coffee,
  Coins,
  CreditCard,
  Droplet,
  Dumbbell,
  Film,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HeartHandshake,
  HeartPulse,
  Home,
  Landmark,
  Laptop,
  LineChart,
  Music,
  Package,
  PawPrint,
  Percent,
  Pill,
  Plane,
  Receipt,
  Repeat,
  Scissors,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Train,
  TrendingUp,
  Truck,
  Umbrella,
  Utensils,
  Vault,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Moliya kategoriyalari uchun ikona kaliti (kebab) → lucide komponent. */
export const FINANCE_ICONS: Record<string, LucideIcon> = {
  wallet: Wallet,
  coins: Coins,
  banknote: Banknote,
  "trending-up": TrendingUp,
  briefcase: Briefcase,
  vault: Vault,
  landmark: Landmark,
  gift: Gift,
  utensils: Utensils,
  "shopping-bag": ShoppingBag,
  shirt: Shirt,
  car: Car,
  bus: Bus,
  fuel: Fuel,
  plane: Plane,
  home: Home,
  receipt: Receipt,
  smartphone: Smartphone,
  "heart-pulse": HeartPulse,
  dumbbell: Dumbbell,
  "graduation-cap": GraduationCap,
  "gamepad-2": Gamepad2,
  coffee: Coffee,
  "shopping-cart": ShoppingCart,
  pill: Pill,
  baby: Baby,
  "paw-print": PawPrint,
  repeat: Repeat,
  percent: Percent,
  "line-chart": LineChart,
  building: Building2,
  film: Film,
  scissors: Scissors,
  book: BookOpen,
  shield: ShieldCheck,
  "heart-handshake": HeartHandshake,
  wrench: Wrench,
  "bed-double": BedDouble,
  droplet: Droplet,
  wifi: Wifi,
  "circle-dashed": CircleDashed,
  "credit-card": CreditCard,
  umbrella: Umbrella,
  zap: Zap,
  flame: Flame,
  train: Train,
  truck: Truck,
  package: Package,
  music: Music,
  cake: Cake,
  laptop: Laptop,
};

/** Kategoriya tanlovida ko'rsatiladigan ikonalar ro'yxati. */
export const FINANCE_ICON_KEYS = Object.keys(FINANCE_ICONS);

/** Kalitni komponentga aylantiradi (noma'lum bo'lsa — CircleDashed). */
export function financeIcon(key: string | null | undefined): LucideIcon {
  return (key && FINANCE_ICONS[key]) || CircleDashed;
}
